"""trying to add photo to user

Revision ID: 8bdd7e61a8dd
Revises: 
Create Date: 2022-08-22 19:05:19.430075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bdd7e61a8dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vartotojas', sa.Column('nuotrauka', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'vartotojas', ['Slaptažodis'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vartotojas', type_='unique')
    op.drop_column('vartotojas', 'nuotrauka')
    # ### end Alembic commands ###
