"""Add phone number

Revision ID: 0c8e11e08305
Revises: 684da3f124c9
Create Date: 2022-07-28 21:44:24.215303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c8e11e08305'
down_revision = '684da3f124c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('age', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'age')
    # ### end Alembic commands ###
